name: Emscripten

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        cc: [ emcc ]
    
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive

    # the xenial emscripten package is old (and doesn't support wasm);
    # this brings in emsdk which is more recent, and does.
    - uses: mymindstorm/setup-emsdk@v7

    - name: dependencies
      run: |
        sudo apt-get update
        sudo apt-get install bmake # wabt is not in xenial
        # emcc -v # first run to generate ~/.emscripten only needed for system package
        emcc -v # informational
        curl https://wasmtime.dev/install.sh -sSf | bash # not packaged for ubuntu
        # . ~/.bashrc for the paths added by wasmtime's installation does not work here
        # I can't figure out why, so I'm just setting the paths by hand.
        export WASMTIME_HOME="$HOME/.wasmtime"
        export PATH="$WASMTIME_HOME/bin:$PATH"
        wasmtime --version

    - name: make
      run: |
        bmake -r -j 2 DEBUG=1 PKGCONF=pkg-config CC=${{ matrix.cc }}

    - name: test
      # wasm-validate is not packaged for xenial
      run: |
        export WASMTIME_HOME="$HOME/.wasmtime"
        export PATH="$WASMTIME_HOME/bin:$PATH"
        bmake -r -j 2 PKGCONF=pkg-config WASM_VALIDATE='true; echo wasm-validate' CC=${{ matrix.cc }} test

    - uses: actions/upload-artifact@v2
      with:
        name: stping-${{ github.sha }}.wasm
        path: build/bin/stping.wasm

